### ISSUE TITLE
make generic code more elegent

### ISSUE THREAD

**Issue by udisun** [stacksight/stacksight-php-sdk#6]
I tend to be a smart ass and change generic lines like these:
https://github.com/stacksight/stacksight-php-sdk/blob/master/SSEventsMessageMapping.php#L45-L54

``` php
               switch ($event['action']) {
                    case 'created':
                        $design['color'] = $color_created;
                        break;
                    case 'updated':
                        $design['color'] = $color_updated;
                        break;
                    case 'deleted':
                        $design['color'] = $color_deleted;
                        break;
                }
```

to be this:

``` php
$design['color'] = ${'color_' . $event['action']};
```

and if you really want to be protective about your allowed actions you could do this:

``` php
if (in_array($event['action'], arary('created', 'updated', 'deleted')) {
  $design['color'] = ${'color_' . $event['action']};
}
```

**Comment by bora89** [comment]
More elegant, but much less readable. Should be less magic here, so programmers knowing classic languages could understand.

**Comment by udisun** [comment]
In this specific example i dont agree with you. The code is still readable and php programmers would understand it. I prefer that then more lines of code with usually means more maintenance and more bugs. The code i suggest would prevent also human errors on change

**Comment by liorkesos** [comment]
I'm actually seconding @bora89 here - Im not a very up to date php developer but I understand the first clause.
Maybe I'm not the example but this is exposed to many people and I'd rather have it readable and simple then elegent in this case.

**Comment by liorkesos** [comment]
After discussing this with my wife (that used to be a developer) she stated then when generalizing a function you could put the beginning of the original code (switch case in comment) and then use @udisun's  more future error safe version..
