### ISSUE TITLE
Creating a socket even when STACKSIGHT_INCLUDE_LOGS is not enabled

### ISSUE THREAD

**Issue by elroimar** [stacksight/stacksight-php-sdk#8]
@igor-lemon 
In Drupal module there is a creation of a socket in SSClientBase even when STACKSIGHT_INCLUDE_LOGS is not enabled. the creation of the socket takes about ~250ms. 

i suggest to create the socket only logs enabled.

**Comment by igor-lemon** [comment]
Ok. I'll check it.

**Comment by igor-lemon** [comment]
Done. Fixed and released new version of module.
